#include "string/automaton.hpp"
#include "string/duval.h"
#include "string/kmp.h"
#include "string/manacher.h"
#include "string/minPresent.hpp"
#include "string/suffixArray.h"
#include "string/trie.hpp"
