#include "math/poly/polyAll.hpp"
#include "math/bigInt.hpp"
#include "math/binom.hpp"
#include "math/mes.hpp"
#include "math/mod.hpp"
#include "math/ntt.hpp"

#include "math/poly/factorial.h"
#include "math/basic.h"
#include "math/basic.h"
#include "math/fft.h"
#include "math/fmt.h"
#include "math/geometry.h"
#include "math/mix.h"
#include "math/numberTheory.h"
